Added wrapper for fetching mnist
kmyim/scikit-dimension pull request #15
Opened 2024-07-16 11:04 UTC by kmyim

2024-07-16 21:12 UTC, johnharveymath requested changes
Looks great, thanks!

2024-07-16 21:12 UTC, johnharveymath commented on skdim/datasets.py
> +
Remove extra line

2024-07-16 21:12 UTC, johnharveymath commented on skdim/datasets.py
> +    """Fetch MNIST dataset of 60000 28x28 greyscale handwritten digits from OpenML.
Seems to be 70000

2024-07-17 09:49 UTC, kmyim commented
Thanks, rectified the error in dimension

2024-07-17 09:50 UTC, merged