Packing numbers integration
kmyim/scikit-dimension pull request #21
Opened 2024-08-18 11:20 UTC by Malinon

It adds global ID estimator based on Packing Numbers

2024-08-20 10:59 UTC, kmyim requested changes
Maybe I don't understand the algorithm well enough, but do we need r1 != r2? Seems that would be an issue when we divide by log(r1) - log(r2) in the algorithm. Tests past so somehow this might not be an issue, maybe you could help clarify...

2024-08-20 10:59 UTC, kmyim commented on skdim/id/_PackingNumbers.py
> +    def __init__(self, r1=1, r2=2, accuracy=0.9, metric="euclidean", iter_number=10):
Default values of r1 and r2 are the same, but this would induce a divide by zero error when we divide by LOG_RS_DIFF

2024-08-20 10:59 UTC, kmyim commented on skdim/id/_PackingNumbers.py
> +        if self.r2 <= 0 or self.r1 <= 0:
Add check for r1 != r2?

2024-08-20 10:59 UTC, kmyim commented on skdim/id/_PackingNumbers.py
> +            if iter_counter > self.iter_number:
Is there are case where the algorithm doesn't converge (in reasonable time?) to satisfy the condition and the while loop goes on forever without the function returning anything? Maybe add a cap on number of times round the loop (say 10x the user specified number of iterations) and throw an exception when the condition is not met within that tolerance (in that case can change while loop to for loop?).

2024-08-27 09:08 UTC, Malinon commented on skdim/id/_PackingNumbers.py
> +        """Initialize the GRIDE object.
Fixed in newest commit

2024-08-27 09:08 UTC, Malinon commented on skdim/id/_PackingNumbers.py
> +        if self.r2 <= 0 or self.r1 <= 0:
Done

2024-09-12 15:50 UTC, kmyim approved these changes
Looks good!

2024-09-12 20:23 UTC, merged